version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: test_mysql
    restart: always
    environment:
      # Mật khẩu root là bắt buộc
      MYSQL_ROOT_PASSWORD: root123456789
      # Tên database tùy chọn
      MYSQL_DATABASE: finance_db

    ports:
      # Ánh xạ cổng (Host:Container)
      - "3306:3306"

    volumes:
      # Lưu trữ dữ liệu vĩnh viễn
      - db_data:/var/lib/mysql

volumes:
  db_data: